### ISSUE TITLE
Clicking on playroom tab opens storybook inside iframe

### ISSUE THREAD

**Issue by tabrez96** [rbardini/storybook-addon-playroom#13]
![image](https://user-images.githubusercontent.com/29143166/83042786-acd1f680-a05f-11ea-9e6d-6ddd18ea3acc.png)

Storybook version: 5.3.19
storybook-addon-playroom: 1.3.0

.storybook/preview.js
```
import { DocsPage, DocsContainer } from '@storybook/addon-docs/blocks';
import { addDecorator, addParameters } from '@storybook/react';
import { INITIAL_VIEWPORTS } from '@storybook/addon-viewport';
import { withPlayroom } from 'storybook-addon-playroom';

addDecorator(withPlayroom);

addParameters({
  viewport: {
    viewports: INITIAL_VIEWPORTS,
  },
  docs: {
    container: DocsContainer,
    page: DocsPage,
  },
  playroom: {
    url: 'http://localhost:9000',
  },
});
```

I have included `storybook-addon-playroom` in `addons` in `main.js` also

**Comment by rbardini** [comment]
Hi @tabrez96!

Is Playroom running at `http://localhost:9000`? The tab is basically an iframe that loads the configured URL, and it should point to a [Playroom server](https://github.com/seek-oss/playroom#getting-started).
