### ISSUE TITLE
Unexpected value 'undefined' declared by the module 'DynamicModule'

### ISSUE THREAD

**Issue by akuntal** [rbardini/storybook-addon-playroom#14]
While implementing with angular components, storybook throw error.
"zone.js:703 Unhandled Promise rejection: Unexpected value 'undefined' declared by the module 'DynamicModule' ; Zone: <root> ; Task: Promise.then ; Value: Error: Unexpected value 'undefined' declared by the module 'DynamicModule'"

**Comment by rbardini** [comment]
Hi @akuntal!

Playroom is only compatible with React right now, so I'm afraid it won't work with Angular components.

**Comment by akuntal** [comment]
Ah! ok, thanks for your response...
