### ISSUE TITLE
Error "<Root><No Display Name /></Root>"

### ISSUE THREAD

**Issue by hazem3500** [rbardini/storybook-addon-playroom#18]
When opening up playroom directly from the server the components appear fine, but when I open playroom from Storybook I get this error
![error](https://live.staticflickr.com/65535/50297515766_80a00b7054_o.png)

Here is my `playroom.config.js`
```jsx
module.exports = {
    components: './src/components/index.tsx',
    outputPath: './dist/playroom',
    port: 4242,
    frameComponent: './src/components/Root/Root.tsx',
    openBrowser: false,
    webpackConfig: () => ({
        module: {
            rules: [
                {
                    test: /\.tsx?$/,
                    include: /components/,
                    exclude: /node_modules/,
                    use: {
                        loader: 'babel-loader',
                        options: {
                            presets: [
                                '@babel/preset-env',
                                '@babel/preset-typescript',
                                '@babel/preset-react',
                            ],
                        },
                    },
                },
            ],
        },
        resolve: {
            extensions: ['.js', '.ts', '.tsx'],
        },
    }),
};
```
and `src/components/index.tsx`
```jsx
export { default as Badge } from './Badge/Badge';
export { default as Root } from './Root/Root';
```
and the component I was opening from storybook
```jsx
import React from 'react';
import {
    Badge as ChakraBadge,
    BadgeProps as ChakraBadgeProps,
} from '@chakra-ui/core';

export type BadgeProps = ChakraBadgeProps;
const Badge: React.FC<BadgeProps> = ({ ...props }) => {
    return <ChakraBadge {...props} />;
};

export default Badge;
```
and the `Root` component if it's relevant
```jsx
import { ChakraProvider } from '@chakra-ui/core';
import React from 'react';
import theme from '../../theme';

export default function Root({ children }) {
    return (
        <ChakraProvider resetCSS theme={theme}>
            {children}
        </ChakraProvider>
    );
}
```
and the scripts in `package.json`
```json
"scripts": {
        "start": "run-p *:start",
        "build": "run-p *:build",
        "storybook:start": "start-storybook -p 6006 -s public",
        "storybook:build": "build-storybook -s public",
        "playroom:start": "playroom start",
        "playroom:build": "playroom build"
    },
```

**Comment by hazem3500** [comment]
Fixed by making `withPlayroom` decorator the first in the decorators array

**Comment by elisehein** [comment]
I'm having the same issue – all fine when running playroom separately, but not when launching from within Storybook.

The `withPlayroom` decorator didn't do anything for me, I can't see it referred to in the public docs so I'm guessing that's an outdated way of configuring playroom?

What did help was adding an explicit `displayName` to the components that were causing the error (mostly ones using `forwardRef`).

@rbardini let me know if that's expected, or if I should open a separate issue.

**Comment by rbardini** [comment]
Hi @elisehein! The `withPlayroom` decorator isn't needed anymore since v2.0.0. You can try changing the position of `storybook-addon-playroom` in your `addons` array, in case you are using other addons.

The `No Display Name` value comes from https://github.com/algolia/react-element-to-jsx-string/commit/dc0f65c, which means the library is not able to find the component name. Defining a `displayName` is one possible solution, but you can also check if the code is not being minified (stripping display names), or implement [`reactElementToJSXStringOptions.displayName`](https://github.com/algolia/react-element-to-jsx-string#reactelementtojsxstringreactelement-options) with an algorithm to find the right display name.
