### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by mancristiana** [rbardini/storybook-addon-playroom#24]
I followed the steps described in the `Installation` section of the addon, but I did not get a working Playroom.
I used Create React App with TypeScript template and Storybook CLI to quickly get started.

# Reproduction steps:

1.`yarn create react-app storybook-addon-playroom-issue --template typescript`
2.`npx sb init`
3.`yarn add storybook-addon-playroom -D`

In .storybook/main.js:
```
module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/preset-create-react-app",
    "storybook-addon-playroom"
  ]
}
```
You can also reproduce this issue using this [GitHub repository](https://github.com/mancristiana/storybook-addon-playroom-issue).

# What happened
I started Storybook using `yarn storybook`, navigated to the Button component and selected Playroom.  I expected to see a Playroom using the code from the story. Instead I got:
![image](https://user-images.githubusercontent.com/17469404/114395545-cbb87900-9b9c-11eb-94a2-ba521a53bf3e.png)

# Possible Solutions
* Make Playroom addon work out of the box with most common scenarios (Create React App)
* Improve documentation

**Comment by rbardini** [comment]
Hi @mancristiana! Thanks for the very detailed issue 🙂

The addon itself does not run Playroom, it's expected that Playroom is already [set up and running](https://github.com/seek-oss/playroom#getting-started). The panel is basically an iframe loading the Playroom page with the right parameters to render the story.

I should make that clearer in the README. Meanwhile, you can take a look at the [example](https://github.com/rbardini/storybook-addon-playroom/tree/master/example) for a minimal setup (including snippets generation, but that's optional).

**Comment by IronSean** [comment]
I ran into the same, assumed installing the add-on would install and configure everything. That explains the need to specify the URL

**Comment by rbardini** [comment]
I added a small setup disclaimer to the README, hope that helps 🙂
