### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by samwalshnz** [rbardini/storybook-addon-playroom#3]
Imagine a world where you could use Storybook stories as Snippets in Playroom. I have _no_ idea how to make this dream come true, however.

**Comment by rbardini** [comment]
I suppose it's doable with a custom Webpack plugin for Storybook, although it probably means building Storybook and Playroom in sequence. I'll give it a try and let you know 🙂

**Comment by rbardini** [comment]
So the loader idea didn't work out, but I've built a successful prototype on top of the [StoryShots addon](https://github.com/storybookjs/storybook/tree/master/addons/storyshots/storyshots-core). I'm now working on removing as much dependencies as possible, and will open a PR as soon as I get to something usable.
