### ISSUE TITLE
Addon not working. 

### ISSUE THREAD

**Issue by Danishkhurshid** [rbardini/storybook-addon-playroom#31]
I followed the steps described in the Installation section of the addon, but I did not get a working Playroom. 
In storybook/main.js:
```
module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/preset-create-react-app",
    "storybook-addon-playroom"
  ]
}
```

Added the url in preview.js: 
```
import '../src/tokens/tokens.css';

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  playroom: {
    url: 'http://localhost:9000',
  },

}
```
Getting the connection reset error. 
<img width="1409" alt="Screenshot 2021-09-09 at 3 31 41 AM" src="https://user-images.githubusercontent.com/19993386/132591945-5a1f658c-3d29-426d-856d-35c97582dfda.png">

**Comment by rbardini** [comment]
Hi @Danishkhurshid! Is Playroom running at http://localhost:9000? If not, please follow [these instructions](https://github.com/seek-oss/playroom#getting-started).
