### ISSUE TITLE
Upgrade to playroom@0.28.0

### ISSUE THREAD

**Issue by bigwoof91** [rbardini/storybook-addon-playroom#36]
Howdy! Enormously thankful for the storybook plugin for playroom!

Wondering if you could upgrade to [`playroom@0.28.0`](https://github.com/seek-oss/playroom/releases/tag/v0.28.0) (dark mode feature! 🌚)?

I'm happy to open a PR for this if that makes life easier!

Thanks in advance for your help here!

**Comment by rbardini** [comment]
Done!
