### ISSUE TITLE
missing export

### ISSUE THREAD

**Issue by MMT-LD** [rbardini/storybook-addon-playroom#38]
Hey! 

When using vite-builder for storybook i'm seeing this error.

`[vite] Internal server error: Missing "./dist/esm/preset/addDecorator.js" export in "storybook-addon-playroom" package`

The path does exist... but it would seem an export is missing.

I confirm that if i remove the exports part of the package.json all works as expected.

**Comment by rbardini** [comment]
Hi @MMT-LD! I don't get what export is missing here, `addDecorator` exports a `decorators` const.

So you removed the entire `exports` field, and it worked? I may need to review the addon's `package.json` file for better Vite builder compatibility.

**Comment by rbardini** [comment]
This should be fixed in [v4.0.0](https://github.com/rbardini/storybook-addon-playroom/releases/tag/v4.0.0).
