### ISSUE TITLE
gen-snippets using ESM

### ISSUE THREAD

**Issue by elisehein** [rbardini/storybook-addon-playroom#43]
I'm running into a cjs/esm issue with `gen-snippets`. I can see there's an esm version of `generateSnippets.js`, but I can't see that called anywhere. The error I'm seeing is:

```
>npx sb-playroom gen-snippets
/path/to/.storybook/preview.js:1
import React from "react";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

My Storybook config files and all stories use ESM syntax. Is there a built-in way to swap between ESM and cjs for the snippet generation script?

**Comment by rbardini** [comment]
Hi @elisehein! The snippet generator currently always uses the CJS version. However, it also uses Babel to compile stories on the fly:

https://github.com/rbardini/storybook-addon-playroom/blob/1a83a79bd88d233b627d3021ab74f015bcc58201/bin/sb-playroom.js#L12-L13

You may [define a different Babel config](https://github.com/rbardini/storybook-addon-playroom#babel-configuration) that matches your project needs. Note that the [example](https://github.com/rbardini/storybook-addon-playroom/tree/master/example) also has config files and stories using ESM syntax. (although `main.js` still uses `module.exports`)

**Comment by elisehein** [comment]
@rbardini Thank you, that's very helpful.

I don't suppose you could help me with a different error I'm getting after replicating the set up in that example?

```
> npx sb-playroom gen-snippets --config-file "./babel.playroom-snippets.config.json"
</path/to/repo>/node_modules/@storybook/react/node_modules/@storybook/channel-postmessage/dist/cjs/index.js:4
var PostmsgTransport=/*#__PURE__*/function(){function PostmsgTransport(config){_classCallCheck(this,PostmsgTransport);this.config=config;this.buffer=void 0;this.handler=void 0;this.connected=void 0;this.buffer=[];this.handler=null;globalWindow.addEventListener('message',this.handleEvent.bind(this),false);// Check whether the config.page parameter has a valid value

TypeError: Cannot read properties of undefined (reading 'addEventListener')
```

Babel config file:

```
{
  "presets": [
    ["@babel/preset-env", { "targets": { "node": "current" } }],
    "@babel/preset-react"
  ]
}
```

Storybook with the playroom addon and playroom on its own run fine.

**Comment by rbardini** [comment]
@elisehein Seems related to https://github.com/storybookjs/storybook/pull/18251. (`globalWindow` is undefined)
