### ISSUE TITLE
Addon causes Storybook 7 to hang/load for a long time and then crash

### ISSUE THREAD

**Issue by elisehein** [rbardini/storybook-addon-playroom#45]
After upgrading to Storybook 7.0.0-beta.47, enabling the playroom addon (v3.0.2) causes Storybook to load stories for a long time and eventually crash. There are no errors reported back from `storybook dev` or `storybook build`, and no errors in the browser console.
 
<img width="752" alt="CleanShot 2023-02-15 at 11 29 04@2x" src="https://user-images.githubusercontent.com/604621/218988179-5fda1c05-4f63-4ff8-8293-6a69d4649125.png">

After a while it crashes at the following line:

<img width="840" alt="CleanShot 2023-02-15 at 11 39 39@2x" src="https://user-images.githubusercontent.com/604621/218990781-e953c295-a898-4edf-b2f7-45f4360b85e6.png">

**Comment by rbardini** [comment]
Hi @elisehein! Thanks for reporting this. I haven't tested the addon with Storybook 7 yet (been waiting for the stable release), but I'll give it a try soon and report back here.

**Comment by noranda** [comment]
@rbardini Any update on this one? Storybook 7 is in RC now and I would LOVE to get this addon working in it.

**Comment by noranda** [comment]
@rbardini Storybook 7 is now in [stable release](https://storybook.js.org/docs/react/migration-guide)! Any chance we could get this plugin upgraded to support it?

**Comment by rbardini** [comment]
@noranda I'll try to release a new major version supporting Storybook 7.0 sometime next week.

**Comment by noranda** [comment]
@rbardini Thanks for this!

**Comment by rbardini** [comment]
No problem! Sorry for the delay, it took more time than I expected. Let me know if you find any issues!
