### ISSUE TITLE
Crash on Storybook 8

### ISSUE THREAD

**Issue by elisehein** [rbardini/storybook-addon-playroom#56]
After upgrading to Storybook 8 (8.0.2), clicking the Playroom tab on a Story crashes the page (nothing shows up). Here are the console errors:

![CleanShot 2024-03-20 at 14 34 37@2x](https://github.com/rbardini/storybook-addon-playroom/assets/604621/596413fd-0580-4d15-ab00-b0eb83ff2999)

Addon version: 5.0.0

I can't say for sure this is new behaviour for SB8, because I never got this plugin working on SB7 either (my issue was [this one](https://github.com/rbardini/storybook-addon-playroom/issues/45)).

**Comment by julrich** [comment]
Would love to see a fix here, too. Might be able to chip in with development, if needed!

**Comment by julrich** [comment]
I have to add, though. After some investigation in our own upgraded SB8, it seems to work on SB for us, see here:
https://64f08cbba622af835d382b4f-xucnzisdfc.chromatic.com/?path=/story/components-button--primary-button

So maybe this is a problem (as you already hinted at) that might have always existed in your case @elisehein?

**Comment by elisehein** [comment]
I'm still experiencing a crash with storybook-playroom-addon@6.0.0 and storybook v 8.2.5 :(

It's now manifesting differently, the stories themselves won't load either, and I get a memory leak error in the console:

![CleanShot 2024-08-07 at 10 33 41@2x](https://github.com/user-attachments/assets/6aa4cd0a-84b9-463e-b106-15b83f98a7bc)

Since others don't seem to be experiencing this, I'll do some more investigating and hopefully open a more relevant issue.
