### ISSUE TITLE
Needs to be loaded before other decorators in preview.js

### ISSUE THREAD

**Issue by ptibbetts** [rbardini/storybook-addon-playroom#6]
Hey,

Thanks for making and releasing this addon, it looks so much better than using knobs.

I have a few components that use the `<Link>` component from `react-router-dom`, which [need to have a decorator added](https://github.com/storybookjs/storybook/issues/769#issuecomment-294082103) to work inside Storybook.

Since I have so many I've added the decorator globally inside `preview.js` with `addDecorator(withMemoryRouter)`, however if I call this decorator **before** `withPlayroom` then my components render as `MemoryRouter is not defined`. 

The workaround is to call the MemoryRouter decorator **after** `addDecorator(withPlayroom)`, I guess so that the playroom decorator grabs the actual story instead of the one decorated with the MemoryRouter(?).

Is it worth mentioning this in the readme? 
I'm also posting this here in case anyone else searches the issues when this happens to them.

**Comment by rbardini** [comment]
Hi @ptibbetts!

This is definitely worth mentioning in the README. Would you be willing to submit a PR? It could be a short note after the decorator code block 🙂

**Comment by ptibbetts** [comment]
Certainly!
